version: '3.8'
services:
  neo-blasting:
    build: .
    container_name: neo_blasting_app
    ports:
      - "8080:4000" # Cambia 3000 por el puerto real de tu app
    volumes:
      - ./data:/app/data # Para que la base de datos SQLite sea persistente
    restart: always
    env_file:
      - .env